cover/urls.py
from django.urls import path

from cover import views

app_name = 'cover'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('image.png/', views.image_generator, name='image_generator'),
]

orly/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cover/', include('cover.urls', namespace='cover')),
    path('', lambda r: redirect('cover:index')),
]

cover/models.py
from django.db import models

# Create your models here.

cover/forms.py
from urllib.parse import urlencode

from django import forms

from cover.utils import COLOR_CODE


class CoverForm(forms.Form):
    COLOR_CHOICES = [(i, str(COLOR_CODE[i])) for i in range(len(COLOR_CODE))]

    title = forms.CharField(required=True, initial='default title')
    top_text = forms.CharField(required=True)
    author = forms.CharField(required=True)
    animal_code = forms.ChoiceField(choices=[(i, i) for i in range(1, 41)])
    color_code = forms.ChoiceField(choices=COLOR_CHOICES)
    guide_text = forms.CharField()
    guide_text_placement = forms.ChoiceField(
            choices=[
                ('bottom_right', 'bottom_right'),
                ('bottom_left', 'bottom_left'),
                ('top_right', 'top_right'),
                ('top_left', 'top_left'),
            ])

    @property
    def get_params(self):
        if hasattr(self, 'cleaned_data'):
            return urlencode(self.cleaned_data)
        return None

cover/views.py
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont

from django.conf import settings
from django.http.response import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render

from cover.forms import CoverForm
from cover.utils import COLOR_CODE


def index(request):
    if request.method == 'POST':
        form = CoverForm(request.POST)
        if form.is_valid():
            pass
    else:
        form = CoverForm()
    return render(request, 'cover/index.html', {'form': form})

def image_generator(request):
    title = request.GET['title']
    top_text = request.GET['top_text']
    author = request.GET['author']
    animal_code = request.GET['animal_code']
    color_index = request.GET['color_code']
    guide_text = request.GET['guide_text']
    guide_text_placement = request.GET['guide_text_placement']

    animal_path = settings.ROOT('assets', 'animal', '{}.png'.format(animal_code))
    animal_im = Image.open(animal_path)
    animal_im = animal_im.resize((400, 400))

    color = COLOR_CODE[int(color_index)]

    canvas_im = Image.new('RGB', (500, 700), (255, 255, 255, 255))
    canvas_im.paste(animal_im, (50, 40))

    ttf_path = settings.ROOT('assets', 'fonts', 'NanumGothicCoding.ttf')  # get a font
    draw = ImageDraw.Draw(canvas_im)  # get a drawing context

    # rectangle_top
    draw.rectangle([20, 0, 480, 10], fill=color)

    # rectangle_middle
    draw.rectangle([20, 400, 480, 510], fill=color)

    # Title
    fnt = ImageFont.truetype(ttf_path, 70)
    draw.text((45, 430), title, font=fnt, fill=(255, 255, 255, 255))

    # Top text
    fnt = ImageFont.truetype(ttf_path, 20)
    draw.text((160, 13), top_text, font=fnt, fill=(0, 0, 0, 255))

    # Author
    fnt = ImageFont.truetype(ttf_path, 25)
    draw.text((360, 655), author, font=fnt, fill=(0, 0, 0, 255))

    # guide_text
    fnt = ImageFont.truetype(ttf_path, 25)
    draw.text((140, 510), guide_text, font=fnt, fill=(0, 0, 0, 255))

    response = HttpResponse(content_type='image/png')
    canvas_im.save(response, format='PNG')
    return response

cover/templates/cover/index.html
{% extends 'cover/layout.html' %}
{% load bootstrap3 %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <form action="" method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" value="Generate O RLY" class="btn btn-primary">
        </form>
      </div>
      <div class="col-sm-6">
        {% if form.get_params %}
          <img src="{% url 'cover:image_generator' %}?{{ form.get_params }}" alt="">
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

cover/templates/cover/layout.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static "bootstrap-3.3.7/css/bootstrap.min.css" %}">
  <style>
    html {
      position: relative;
      min-height: 100%;
    }
    body {
      margin-bottom: 60px; /* Margin bottom by footer height */
    }
    .footer {
      position: absolute;
      bottom: 0;
      width: 100%;
      height: 60px; /* Set the fixed height of the footer here */
      line-height: 60px; /* Vertically center the text there */
      background-color: #f5f5f5;
    }
  </style>
  <title>Cover Generator</title>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Cover Generator</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
{% block content %}
{% endblock %}
<footer class="footer">
  <div class="container">
    <span class="text-muted">covert genrator by python & django</span>
  </div>
</footer>
<script src="{% static "jquery-3.2.1.min.js" %}"></script>
<script src="{% static "bootstrap-3.3.7/js/bootstrap.min.js" %}"></script>
</body>
</html>